### ISSUE TITLE
Identify key Pact core assets - Update to Ruby 3.1 - Document Pact Universe

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/devrel#10]
# Aim

- Identify all Ruby codebases which need updating to Ruby 3.1 or higher
- Identify all consumers of ruby codebases
- Document "Rube Goldberg" machine for
  - Pact Ruby Reference Core as referenced [here](https://github.com/pact-foundation/devrel#dependency-graph-of-doom) in the dependency graph of doom
  - Pact Rust Reference Core
- Update to at least, Ruby 3.1, preferably Ruby 3.2 across all affected repos
- Update all affected repos
- Test all affected repos

## Why?

- Users of our pact-ruby-standalone project, have been stuck on a packaged Ruby 2.4 run-time due to the build system traveling-ruby, being out-of-maintainence. It has been revived by your very own Devo Avo, into the 21st century with
  - Update to Ruby 3.1.2 & 3.2.2
  - Support for Arm64 Darwin
  - Support for Aarch64 Linux
  - Support for x86 and x64 windows

## What happened?

- pact-ruby-standlaone 2.0.0 was released
- Issues identified by users / maintainers
  -  Requirement to install `libyaml-dev` for debian based users
-  Error when writing pact files for `pact-go-v1` where users are asked to pin the version of the standalone, but provided a script which returns the latest.

## Root cause?

- An error in `pact_mock-service` was reproducible in CI, when using Ruby `3.2.2`
  - Downgrading to Ruby `3.1.2` resolved the issue.

## What are we doing about it?

- Set `pact-ruby-standalone` `2.0.0` release to `pre-release` rather than `latest` to avoid breaking existing users scripts
- Updated `pact-ruby-standalone` `install.sh` script to allow users to fix to particular tag when downloading, over its previous behaviour of using `latest`
- Updating all ruby gems to be tested from `2.7` through to `3.2` in CI across
  - macOS / windows / linux
    - x86_64 versions
  - macOS / linux
    - arm64 versions
- Identifying the root cause of the error above, stopping us moving to `3.2` and looking to help resolve
- Releasing pact-ruby-standalone with ruby `3.1.2`
- Releasing `homebrew-pact-ruby-standalone` with versioned revisions so you can switch between or pin in your CI

## But aren't we moving to the rust core?

Yes! But we understand not all languages are there right now, and we don't have 100% feature parity in the `pact-ruby-standalone` package compared to the Rust reference core. There is actually very little, with potentially the only limitation being the `pact_broker-client` functionality. 

Happy to be shown otherwise! If anyone is interested in build out CLI tools in Rust, we have some examples you can follow, if anyone wanted to make a Rust based implementation of the `pact_broker-client`. Whilst we know it has value, the core maintainers are busy delivering other features, and fixes to users, and therefore it isn't something we are likely to pick up soon, but we are _always_ happy to guide.

### Related issues

- https://github.com/rapid7/metasploit-framework/issues/17593

## Repositories affected and associated PR's

- Pact Broker Client
  - https://github.com/pact-foundation/pact_broker-client/pull/134
- Pact Provider Verifier
  - https://github.com/pact-foundation/pact-provider-verifier/pull/103
- Pact Support
  - https://github.com/pact-foundation/pact-support/pull/98
- Pact Message Ruby
  - https://github.com/pact-foundation/pact-message-ruby/pull/22
- Pact Mock Service
  - https://github.com/pact-foundation/pact-mock_service/pull/141
- Pact Ruby
  - https://github.com/pact-foundation/pact-ruby/pull/292
  - https://github.com/pact-foundation/pact-ruby/pull/293
- Pact Ruby Standalone
  - Pact Ruby Stadalone
    - Ruby 3.1
    - Ruby 3.2 https://github.com/pact-foundation/pact-ruby-standalone/pull/100
  - Homebrew Pact Ruby Standalone
    - https://github.com/pact-foundation/homebrew-pact-ruby-standalone/pull/92
  - Pact-Js-Core 
    -  9.x
      - https://github.com/pact-foundation/pact-js-core/tree/pact-node
    - 13.x
      - https://github.com/pact-foundation/pact-js-core/pull/445 
  - Pact-Python
    - https://github.com/pact-foundation/pact-python/pull/342 
  - Pact-PHP
    - https://github.com/pact-foundation/pact-php/pull/309
  - Pact-Net 3.x
    - https://github.com/pact-foundation/pact-net/tree/release/3.x
  - Pact-Go 1.x
    - https://github.com/pact-foundation/pact-go

## Dependency chain releasing instructions

> _Note_ Some of these are out of date, or don't have release note pages, so will be captured for snagging

* [pact-support gem][pact-support-gem]
    * [pact-mock_service gem][pact-mock-service-gem]
        * [pact-ruby-standalone][pact-ruby-standalone]
    * [pact gem][pact-gem]
        * [pact-ruby-standalone][pact-ruby-standalone]
        * [pact-provider-verifier gem][pact-provider-verifier-gem]
        * [pact-cli-docker][pact-cli-docker]

* [pact ruby standalone package][pact-ruby-standalone]
    * [pact-python][pact-python]
    * [pact-net][pact-net]
    * [pact-php][pact-php]            
    * [pact-js-core][pact-js-core]
        * [pact-js][pact-js]         
    * [pact-go][pact-go]
    * [pact-consumer-swift][pact-consumer-swift]

[pact-support-gem]: https://github.com/pact-foundation/pact-support/blob/master/RELEASING.md
[pact-mock-service-gem]: https://github.com/pact-foundation/pact-mock_service/blob/master/RELEASING.md
[pact-mock-service-standalone]: https://github.com/pact-foundation/pact-mock_service/blob/master/packaging/README.md
[pact-gem]: https://github.com/pact-foundation/pact-support/blob/master/RELEASING.md
[pact-mock-service-npm]: https://github.com/pact-foundation/pact-mock-service-npm/blob/master/RELEASING.md
[pact-js-core]: https://github.com/pact-foundation/pact-js-core/blob/master/RELEASING.md
[pact-js]: https://github.com/pact-foundation/pact-js/blob/master/RELEASING.md
[pact-provider-verifier-gem]: https://github.com/pact-foundation/pact-provider-verifier/blob/master/RELEASING.md
[pact-provider-verifier-standalone]: https://github.com/pact-foundation/pact-provider-verifier/blob/master/RELEASING.md
[pact-provider-verifier-docker]: https://github.com/DiUS/pact-provider-verifier-docker/blob/master/RELEASING.md
[pact-broker-gem]: https://github.com/pact-foundation/pact_broker/blob/master/RELEASING.md
[pact-python]: https://github.com/pact-foundation/pact-python/blob/master/RELEASING.md
[pact-ruby-standalone]: https://github.com/pact-foundation/pact-ruby-standalone/blob/master/RELEASING.md
[pact-standalone-npm]: https://github.com/pact-foundation/pact-standalone-npm/blob/master/RELEASING.md
[pact-go]: https://github.com/pact-foundation/pact-go/blob/master/RELEASING.md
[pact-net]: https://github.com/pact-foundation/pact-net
[pact-cli-docker]: https://github.com/pact-foundation/pact-ruby-cli
[pact-consumer-swift]: https://github.com/DiUS/pact-consumer-swift
[pact-php]: https://github.com/pact-foundation/pact-php

## Ruby Goldberg Machine

```mermaid
graph TD;
    pact-support;
    pact-support-->pact-mock_service;
    pact-support-->pact-message;
    pact-mock_service-->pact-message;
    pact-message-->pact-provider-verifier;
    pact-->pact-provider-verifier;
    pact_broker-client;
    pact-->pact-ruby-standalone;
    pact-mock_service-->pact-ruby-standalone;
    pact-support-->pact-ruby-standalone;
    pact-provider-verifier-->pact-ruby-standalone;
    pact_broker-client-->pact-ruby-standalone;
    pact-message-->pact-ruby-standalone;
    pact-->pact-ruby-cli;
    pact-ruby-standalone-->homebrew-pact-ruby-standalone;
    pact-ruby-standalone-->pact-python;
    pact-ruby-standalone-->pact-php;
    pact-ruby-standalone-->pact-node-->pact-js-v9;
    pact-ruby-standalone-->pact-js-core-->pact-js-v10
    pact-js-v9-->jest-pact;
    pact-js-v9-->mocha-pact;
    pact-js-v9-->nestjs-pact;
    pact-js-v10-->jest-pact;
    pact-js-v10-->nestjs-pact;
    pact-ruby-standalone-->pact-go-v1;
    pact-ruby-standalone-->pact-net;
    pact-ruby-standalone-->pact-consumer-swift;
```

## Ruby Standalone Consumers Goldberg Machine

```mermaid
graph TD;
    pact-->pact-ruby-standalone;
    pact-mock_service-->pact-ruby-standalone;
    pact-support-->pact-ruby-standalone;
    pact-provider-verifier-->pact-ruby-standalone;
    pact_broker-client-->pact-ruby-standalone;
    pact-message-->pact-ruby-standalone;
    pact-ruby-standalone-->homebrew-pact-ruby-standalone;
    pact-ruby-standalone-->pact-python;
    pact-ruby-standalone-->pact-php;
    pact-ruby-standalone-->pact-node-->pact-js-v9;
    pact-ruby-standalone-->pact-js-core-->pact-js-v10
    pact-js-v9-->jest-pact;
    pact-js-v9-->mocha-pact;
    pact-js-v9-->nestjs-pact;
    pact-js-v10-->jest-pact;
    pact-js-v10-->nestjs-pact;
    pact-ruby-standalone-->pact-go-v1;
    pact-ruby-standalone-->pact-net;
    pact-ruby-standalone-->pact-consumer-swift;
```

### Rust Goldberg machine

```mermaid
graph TD;
    pact_cli;
    pact_models-->pact_cli;
    pact_matching-->pact_cli;
    pact_consumer;
    pact_models-->pact_consumer;
    pact_matching-->pact_consumer;
    pact_mock_server-->pact_consumer;
    pact_ffi;
    pact_matching-->pact_ffi;
    pact_models-->pact_ffi;
    pact_mock_server-->pact_ffi;
    pact_verifier-->pact_ffi;
    pact_matching;
    pact_models-->pact_matching;
    pact_mock_server;
    pact_matching-->pact_mock_server;
    pact_models-->pact_mock_server;
    pact_mock_server_cli;
    pact_matching-->pact_mock_server_cli;
    pact_models-->pact_mock_server_cli;
    pact_mock_server-->pact_mock_server_cli;
    pact_models;
    pact_verifier;
    pact_matching-->pact_verifier;
    pact_models-->pact_verifier;
    pact-plugin-driver-->pact_verifier;
    pact_verifier_cli;
    pact_models-->pact_verifier_cli;
    pact_verifier-->pact_verifier_cli;
    pact_wasm;
    pact_models-->pact_wasm;
    pact-plugin-driver;
    pact_models-->pact-plugin-driver;
    pact_ffi-->pact-js-core-->pact-js-v10;
    pact-js-v10-->jest-pact;
    pact_ffi-->pact-net-v4;
    pact_ffi-->pact-go-v2;
    pact_ffi-->pact-swift-->pact-swift-examples;
    pact_ffi-->pact-dart;
    pact_ffi-->pact-cplusplus;
    pact_mock_server-->pact_elixir;
```

### Rust FFI Consumers Goldberg machine

```mermaid
graph TD;
    pact_ffi;
    pact_ffi-->pact-js-core-->pact-js-v10;
    pact-js-v10-->jest-pact;
    pact_ffi-->pact-net-v4;
    pact_ffi-->pact-go-v2;
    pact_ffi-->pact-swift-->pact-swift-examples;
    pact_ffi-->pact-dart;
    pact_ffi-->pact-cplusplus;
```

### Java Goldberg machine

```mermaid
graph TD;
    pact_jvm;
    pact_jvm-->pact4s;
```

## Versions

Tested using

- traveling ruby release https://github.com/YOU54F/traveling-ruby/releases/tag/rel-20230504
  - with Ruby 3.1.2
- pact-ruby-standalone release https://github.com/YOU54F/pact-ruby-standalone/releases/tag/v2.2.1
  - with Ruby 3.1.4

## Test runs

- homebrew-pact-ruby-standalone 
  - x86_64
  - arm64
- pact-python
  - x86_64 https://github.com/YOU54F/pact-python/actions/runs/4941346866
  - arm64 https://cirrus-ci.com/build/6108629787475968
- pact-node
  - x86_64 https://github.com/YOU54F/pact-js-core/actions/runs/4941248126
  - arm64 https://cirrus-ci.com/build/5418915182936064
- pact-js-core
  - x86_64 https://github.com/YOU54F/pact-js-core/actions/runs/4941170981
  - arm64 https://cirrus-ci.com/build/5969803895111680
- pact-php
  - x86_64 https://github.com/YOU54F/pact-php/actions/runs/4941467873
  - arm64 https://cirrus-ci.com/build/5862300863692800
- pact-go-v1
  - x86_64 https://github.com/YOU54F/pact-go/actions/runs/4941862361
  - arm64 https://cirrus-ci.com/build/6622000215490560
- pact-net
  - x86_64
  - arm64
- pact-consumer-swift
  - x86_64
  - arm64
- example-consumer-golang
  - https://github.com/pactflow/example-consumer-golang/actions/runs/4941971784

**Comment by TimothyJones** [comment]
AMAZING work, @YOU54F!

**Comment by YOU54F** [comment]
So the big update is complete and working well.

The pact ecosystem is documented here 

https://docs.pact.io/diagrams/ecosystem

I need to provide some more links to the ruby libraries on the website at some point.

Thanks for the kind words Tim :)
